services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /opt/appdata/mediaserver/config/jellyfin:/config
      - /opt/appdata/mediaserver/cache/jellyfin:/cache
      - /mnt/storage/media:/data/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    labels:
      - glance.name=Jellyfin
      - glance.description=Media Player
      - glance.url=http://${SERVER_IP}:8096
      - glance.icon=si:jellyfin
      - glance.category=media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /opt/appdata/mediaserver/config/sonarr:/config
      - /mnt/storage:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    labels:
      - glance.name=Sonarr
      - glance.description=TV Shows Organizer/Manager
      - glance.url=http://${SERVER_IP}:8989
      - glance.icon=si:sonarr
      - glance.category=media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /opt/appdata/mediaserver/config/radarr:/config
      - /mnt/storage:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    labels:
      - glance.name=Radarr
      - glance.description=Movie Organizer/Manager
      - glance.url=http://${SERVER_IP}:7878
      - glance.icon=si:radarr
      - glance.category=media

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - /opt/appdata/mediaserver/config/bazarr:/config
      - /mnt/storage/media:/data/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    labels:
      - glance.name=Bazarr
      - glance.description=Subtitle Manager
      - glance.url=http://${SERVER_IP}:6767
      - glance.icon=sh:bazarr-light
      - glance.category=media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - /opt/appdata/mediaserver/config/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    labels:
      - glance.name=Prowlarr
      - glance.description=Indexer Manager
      - glance.url=http://${SERVER_IP}:9696
      - glance.icon=sh:prowlarr-light
      - glance.category=media

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    labels:
      - glance.name=Byparr
      - glance.description=Cloudflare ByPass
      - glance.icon=sh:byparr-light
      - glance.category=media

  gluetun: 
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    ports:
      - 9091:9091
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - SERVER_REGIONS=${SERVER_REGIONS}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      - glance.name=Gluetun
      - glance.category=media
      - glance.parent=transmission
      
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      gluetun:
        condition: service_started
    restart: unless-stopped
    network_mode: "service:gluetun"
    # ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    volumes:
      - /opt/appdata/mediaserver/config/transmission:/config
      - /opt/appdata/mediaserver/data/torrents/incomplete:/data/torrents/incomplete
      - /mnt/storage/torrents/complete:/data/torrents/complete
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWD}
    labels:
      - glance.name=Transmission
      - glance.description=Torrent Client & VPN
      - glance.url=http://${SERVER_IP}:9091
      - glance.icon=si:transmission
      - glance.category=media
      - glance.id=transmission

networks:
  default:
    name: media_network
