services:
  n8n-init:
    image: busybox:stable
    container_name: n8n-init
    volumes:
      - app_data:/home/node/.n8n
    command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
    labels:
      - glance.name=N8N Init
      - glance.parent=n8n
      - glance.category=default
      - glance.hide=true

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    depends_on:
      n8n-init:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - app_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      # - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      # - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_PROXY_HOPS=1
    labels:
      - glance.name=N8N
      - glance.description=AI Workflow Automation
      - glance.url=https://{SUBDOMAIN}.${DOMAIN_NAME}
      - glance.icon=si:n8n
      - glance.category=default
      - glance.id=n8n

networks:
  default:
    name: n8n_network

volumes:
    app_data:
