services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - config:/config
      - /var/run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Istanbul
    privileged: true
    labels:
      - glance.name=Home Assistant
      - glance.description=Home Automation
      - glance.url=http://${SERVER-IP}:8123
      - glance.icon=si:homeassistant
      - glance.category=default

volumes:
    config:
