services:
  app:
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - config:/opt/adguardhome/conf
      - data:/opt/adguardhome/work
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '3000:3000' # used only initial setup
      # - '80:80' # used until reverse proxy is installed
    networks:
      - network

volumes:
  config:
  data:
  
networks:
  network:
