services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8096:8096
    volumes:
      - /opt/media/config/jellyfin:/config
      - /opt/media/cache/jellyfin:/cache
      - /opt/media/movies:/movies
      - /opt/media/tv-shows:/tv-shows
