services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - /opt/appdata/glance:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - glance.name=Glance
      - glance.description=Dashboard
      - glance.url=http://${SERVER-IP}:80
      - glance.icon=di:glance
      - glance.category=default
      - glance.id=glance

  glance-transmission:
    image: ghcr.io/xtrems876/glance-transmission:latest
    container_name: glance-transmission
    restart: unless-stopped
    ports:
      - 9092:8080
    labels:
      - glance.name=Glance Transmission
      - glance.url=http://${SERVER-IP}:9092
      - glance.category=default
      - glance.parent=glance

networks:
  default:
    name: glance_network
